ALTER TABLE rent
    MODIFY price DECIMAL(10, 2) NULL,
    ADD COLUMN price_to DECIMAL(10, 2) NULL AFTER price,
    ADD COLUMN negotiable BOOLEAN NOT NULL DEFAULT FALSE AFTER top,
    ADD COLUMN hide_phone BOOLEAN NOT NULL DEFAULT FALSE AFTER negotiable;

use naimudb;
