ALTER TABLE service
    MODIFY price DECIMAL(10, 2) NULL,
    ADD COLUMN price_to DECIMAL(10, 2) NULL AFTER price,
    ADD COLUMN on_site BOOLEAN NOT NULL DEFAULT 0 AFTER address,
    ADD COLUMN negotiable BOOLEAN NOT NULL DEFAULT 0 AFTER top,
    ADD COLUMN hide_phone BOOLEAN NOT NULL DEFAULT 0 AFTER negotiable;

use naimudb;
