ALTER TABLE rent_ad
    MODIFY price BIGINT NULL,
    ADD COLUMN price_to BIGINT NULL AFTER price,
    ADD COLUMN negotiable BOOLEAN NOT NULL DEFAULT FALSE AFTER top,
    ADD COLUMN hide_phone BOOLEAN NOT NULL DEFAULT FALSE AFTER negotiable;

use naimudb;
