ALTER TABLE ad
    ADD COLUMN on_site BOOLEAN NOT NULL DEFAULT FALSE AFTER address,
    MODIFY price DECIMAL(10, 2) NULL,
    ADD COLUMN price_to DECIMAL(10, 2) NULL AFTER price,
    ADD COLUMN negotiable BOOLEAN NOT NULL DEFAULT FALSE AFTER price_to,
    ADD COLUMN hide_phone BOOLEAN NOT NULL DEFAULT FALSE AFTER negotiable;
