ALTER TABLE ad
    ADD COLUMN on_site BOOLEAN NOT NULL DEFAULT FALSE AFTER address,
    MODIFY price BIGINT NULL,
    ADD COLUMN price_to BIGINT NULL AFTER price,
    ADD COLUMN negotiable BOOLEAN NOT NULL DEFAULT FALSE AFTER price_to,
    ADD COLUMN hide_phone BOOLEAN NOT NULL DEFAULT FALSE AFTER negotiable;
